// This file is automatically generated. Do not modify it manually.

import { FirebaseOptions } from 'firebase/app';

// This is a PUBLIC configuration object. It's safe to include in client-side code.
// Your Firebase security rules are responsible for protecting your data.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "API_KEY",
  authDomain: "PROJECT_ID.firebaseapp.com",
  projectId: "PROJECT_ID",
  storageBucket: "PROJECT_ID.appspot.com",
  messagingSenderId: "SENDER_ID",
  appId: "APP_ID",
};
